### PR TITLE
Simplified code in IsStringInArray() function

### PR DESCRIPTION
**Pull request by larsewi**

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Review by olehermanse — APPROVED** [review]
* Docstring 👍 
* More asserts 👍 
* More standard loop condition 👍 
* Early return when found 👍 

Probably the performance change is insignificant, but it makes sense to me :)

**Comment by vpodzime** [comment]
> Probably the performance change is insignificant

What performance change? There can't be any. The loop was just testing `!found` so it had an early exit already. And it had a standard condition for a `for` loop with an early exit.

The other things are definitely nice.

**Comment by olehermanse** [comment]
> What performance change? There can't be any. The loop was just testing !found so it had an early exit already. And it had a standard condition for a for loop with an early exit.

@vpodzime ah yep, sorry, you're right. I was initially thinking it would loop through the whole thing. It would be interesting to see if this got optimized to exactly the same instructions or not, there are some subtle differences (having a variable vs not having one, where the condition is checked, etc.), but it probably doesn't matter anyway.

**Comment by vpodzime** [comment]
> if this got optimized to exactly the same instructions or not

Yup. But I'm quite sure it would be the same or very similar.

**Comment by larsewi** [comment]
I couldn't help myself...
```C
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static inline bool IsStringInArrayV1(const char *str, const char *const *array,
                                     size_t n_items) {
  bool found = false;
  for (size_t i = 0; !found && (i < n_items); i++) {
    found = strcmp(array[i], str) != 0;
  }
  return found;
}

static inline bool IsStringInArrayV2(const char *const str,
                                     const char *const *const array,
                                     const size_t n_items) {
  for (size_t i = 0; i < n_items; i++) {
    if (strcmp(array[i], str) != 0) {
      return true;
    }
  }
  return false;
}

int main(int argc, char *argv[]) {
  IsStringInArrayV1(argv[1], (const char *const *)argv + 2, argc - 2);
  IsStringInArrayV2(argv[1], (const char *const *)argv + 2, argc - 2);
  return 0;
}
```

```console
$ gcc -S main.c
```

```asm
	.p2align	4, 0x90                         ## -- Begin function IsStringInArrayV1
_IsStringInArrayV1:                     ## @IsStringInArrayV1
	.cfi_startproc
## %bb.0:
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	subq	$48, %rsp
	movq	%rdi, -8(%rbp)
	movq	%rsi, -16(%rbp)
	movq	%rdx, -24(%rbp)
	movb	$0, -25(%rbp)
	movq	$0, -40(%rbp)
LBB1_1:                                 ## =>This Inner Loop Header: Depth=1
	xorl	%eax, %eax
                                        ## kill: def $al killed $al killed $eax
	testb	$1, -25(%rbp)
	movb	%al, -41(%rbp)                  ## 1-byte Spill
	jne	LBB1_3
## %bb.2:                               ##   in Loop: Header=BB1_1 Depth=1
	movq	-40(%rbp), %rax
	cmpq	-24(%rbp), %rax
	setb	%al
	movb	%al, -41(%rbp)                  ## 1-byte Spill
LBB1_3:                                 ##   in Loop: Header=BB1_1 Depth=1
	movb	-41(%rbp), %al                  ## 1-byte Reload
	testb	$1, %al
	jne	LBB1_4
	jmp	LBB1_6
LBB1_4:                                 ##   in Loop: Header=BB1_1 Depth=1
	movq	-16(%rbp), %rax
	movq	-40(%rbp), %rcx
	movq	(%rax,%rcx,8), %rdi
	movq	-8(%rbp), %rsi
	callq	_strcmp
	cmpl	$0, %eax
	setne	%al
	andb	$1, %al
	movb	%al, -25(%rbp)
## %bb.5:                               ##   in Loop: Header=BB1_1 Depth=1
	movq	-40(%rbp), %rax
	addq	$1, %rax
	movq	%rax, -40(%rbp)
	jmp	LBB1_1
LBB1_6:
	movb	-25(%rbp), %al
	andb	$1, %al
	movzbl	%al, %eax
	addq	$48, %rsp
	popq	%rbp
	retq
	.cfi_endproc
                                        ## -- End function
	.p2align	4, 0x90                         ## -- Begin function IsStringInArrayV2
_IsStringInArrayV2:                     ## @IsStringInArrayV2
	.cfi_startproc
## %bb.0:
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	subq	$48, %rsp
	movq	%rdi, -16(%rbp)
	movq	%rsi, -24(%rbp)
	movq	%rdx, -32(%rbp)
	movq	$0, -40(%rbp)
LBB2_1:                                 ## =>This Inner Loop Header: Depth=1
	movq	-40(%rbp), %rax
	cmpq	-32(%rbp), %rax
	jae	LBB2_6
## %bb.2:                               ##   in Loop: Header=BB2_1 Depth=1
	movq	-24(%rbp), %rax
	movq	-40(%rbp), %rcx
	movq	(%rax,%rcx,8), %rdi
	movq	-16(%rbp), %rsi
	callq	_strcmp
	cmpl	$0, %eax
	je	LBB2_4
## %bb.3:
	movb	$1, -1(%rbp)
	jmp	LBB2_7
LBB2_4:                                 ##   in Loop: Header=BB2_1 Depth=1
	jmp	LBB2_5
LBB2_5:                                 ##   in Loop: Header=BB2_1 Depth=1
	movq	-40(%rbp), %rax
	addq	$1, %rax
	movq	%rax, -40(%rbp)
	jmp	LBB2_1
LBB2_6:
	movb	$0, -1(%rbp)
LBB2_7:
	movb	-1(%rbp), %al
	andb	$1, %al
	movzbl	%al, %eax
	addq	$48, %rsp
	popq	%rbp
	retq
	.cfi_endproc
                                        ## -- End function
```

```diff
1,2c1,2
< 	.p2align	4, 0x90                         ## -- Begin function IsStringInArrayV1
< _IsStringInArrayV1:                     ## @IsStringInArrayV1
---
> 	.p2align	4, 0x90                         ## -- Begin function IsStringInArrayV2
> _IsStringInArrayV2:                     ## @IsStringInArrayV2
11,14c11,13
< 	movq	%rdi, -8(%rbp)
< 	movq	%rsi, -16(%rbp)
< 	movq	%rdx, -24(%rbp)
< 	movb	$0, -25(%rbp)
---
> 	movq	%rdi, -16(%rbp)
> 	movq	%rsi, -24(%rbp)
> 	movq	%rdx, -32(%rbp)
16,22c15
< LBB1_1:                                 ## =>This Inner Loop Header: Depth=1
< 	xorl	%eax, %eax
<                                         ## kill: def $al killed $al killed $eax
< 	testb	$1, -25(%rbp)
< 	movb	%al, -41(%rbp)                  ## 1-byte Spill
< 	jne	LBB1_3
< ## %bb.2:                               ##   in Loop: Header=BB1_1 Depth=1
---
> LBB2_1:                                 ## =>This Inner Loop Header: Depth=1
24,33c17,20
< 	cmpq	-24(%rbp), %rax
< 	setb	%al
< 	movb	%al, -41(%rbp)                  ## 1-byte Spill
< LBB1_3:                                 ##   in Loop: Header=BB1_1 Depth=1
< 	movb	-41(%rbp), %al                  ## 1-byte Reload
< 	testb	$1, %al
< 	jne	LBB1_4
< 	jmp	LBB1_6
< LBB1_4:                                 ##   in Loop: Header=BB1_1 Depth=1
< 	movq	-16(%rbp), %rax
---
> 	cmpq	-32(%rbp), %rax
> 	jae	LBB2_6
> ## %bb.2:                               ##   in Loop: Header=BB2_1 Depth=1
> 	movq	-24(%rbp), %rax
36c23
< 	movq	-8(%rbp), %rsi
---
> 	movq	-16(%rbp), %rsi
39,42c26,32
< 	setne	%al
< 	andb	$1, %al
< 	movb	%al, -25(%rbp)
< ## %bb.5:                               ##   in Loop: Header=BB1_1 Depth=1
---
> 	je	LBB2_4
> ## %bb.3:
> 	movb	$1, -1(%rbp)
> 	jmp	LBB2_7
> LBB2_4:                                 ##   in Loop: Header=BB2_1 Depth=1
> 	jmp	LBB2_5
> LBB2_5:                                 ##   in Loop: Header=BB2_1 Depth=1
46,48c36,40
< 	jmp	LBB1_1
< LBB1_6:
< 	movb	-25(%rbp), %al
---
> 	jmp	LBB2_1
> LBB2_6:
> 	movb	$0, -1(%rbp)
> LBB2_7:
> 	movb	-1(%rbp), %al
```

* `IsStringInArrayV1()` contains 56 lines
* `IsStringInArrayV2()` contains 48 lines

However, it might be the same if we optimize 😉

**Comment by vpodzime** [comment]
> ```c
> 
> static inline bool IsStringInArrayV1(const char *str, const char *const *array,
>                                      size_t n_items) {
> ```

Missing `const` in front of `size_t n_items`. Could potentially make a difference ;)

**Comment by vpodzime** [comment]
> Also interesting to see that the compiler does not `inline` the functions

What makes you think they are not inlined?

**Comment by larsewi** [comment]
> Missing const in front of size_t n_items. Could potentially make a difference 😉

This is one of the improvements I made.

> What makes you think they are not inlined?

Because:
```
	pushq	%rbp  ## Old frame pointer is stored
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp ## New frame pointer is loaded
	.cfi_def_cfa_register %rbp
	subq	$48, %rsp ## Space reserved for local variables on the stack
	## Arguments are loaded into registers
	movq	%rdi, -8(%rbp) 
	movq	%rsi, -16(%rbp)
	movq	%rdx, -24(%rbp)
	movb	$0, -25(%rbp)
	movq	$0, -40(%rbp)
```
looks like the start of a function call to me

**Comment by olehermanse** [comment]
@larsewi That's the inlining :) There's no `call` there, but probably ways to reduce the number of instructions in this case.

**Comment by larsewi** [comment]
Here is a copy of `main()` for reference
```asm
_main:                                  ## @main
	.cfi_startproc
## %bb.0:
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
	subq	$16, %rsp
	movl	$0, -4(%rbp)
	movl	%edi, -8(%rbp)
	movq	%rsi, -16(%rbp)
	movq	-16(%rbp), %rax
	movq	8(%rax), %rdi
	movq	-16(%rbp), %rsi
	addq	$16, %rsi
	movl	-8(%rbp), %eax
	subl	$2, %eax
	movslq	%eax, %rdx
	callq	_IsStringInArrayV1
	movq	-16(%rbp), %rax
	movq	8(%rax), %rdi
	movq	-16(%rbp), %rsi
	addq	$16, %rsi
	movl	-8(%rbp), %eax
	subl	$2, %eax
	movslq	%eax, %rdx
	callq	_IsStringInArrayV2
	xorl	%eax, %eax
	addq	$16, %rsp
	popq	%rbp
	retq
	.cfi_endproc

```

**Comment by vpodzime** [comment]
Actually (fn1.c being `V1` above, fn2.c being `V2` above, just both with the `strcmp()` condition fixed):
```
[vpodzime@vp-desktop outs]$ gcc -S ../fn1.c 
[vpodzime@vp-desktop outs]$ wc -l fn*.s
  51 fn1.s
  57 fn2.s
[vpodzime@vp-desktop outs]$ gcc -O1 -S ../fn2.c 
[vpodzime@vp-desktop outs]$ wc -l fn*.s
  51 fn1.s
  70 fn2.s
 121 total
[vpodzime@vp-desktop outs]$ gcc -O2 -S ../fn2.c 
[vpodzime@vp-desktop outs]$ wc -l fn*.s
  51 fn1.s
  82 fn2.s
 133 total
[vpodzime@vp-desktop outs]$ gcc -Os -S ../fn2.c 
[vpodzime@vp-desktop outs]$ wc -l fn*.s
  51 fn1.s
  57 fn2.s
 108 total
```

**Pull request merged**
